from datetime import date
from Funciones import Familiar,Mascota

padre = Familiar('Antonio','Montagna',date(1954,2,17),'Padre')
print(padre.nombre)
print(padre.apellido)
print(padre.nacimiento)
print(padre.edad)
print(padre.vinculo)
print(padre.especie)
print('\n')

madre = Familiar('Maite','Garzo',date(1954,5,14),'Madre')
print(madre.nombre)
print(madre.apellido)
print(madre.nacimiento)
print(madre.edad)
print(madre.vinculo)
print(madre.especie)
print('\n')

hermano = Familiar('Alejo','Verlino',date(1985,4,13),'Hermano')
print(hermano.nombre)
print(hermano.apellido)
print(hermano.nacimiento)
print(hermano.edad)
print(hermano.vinculo)
print(hermano.especie)
print('\n')

novia = Familiar('Maria Agustina','Peralta',date(1993,10,25),'Novia')
print(novia.nombre)
print(novia.apellido)
print(novia.nacimiento)
print(novia.edad)
print(novia.vinculo)
print(novia.especie)
print('\n')

wanda = Mascota('Wanda',date(2021,9,26))
print(wanda.nombre)
print(wanda.adopcion)
print(wanda.especie)
print('\n')