# Generated by Django 4.0.4 on 2022-06-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntregable', '0004_rename_nombre_libro_nombre_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='link_autor',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='link_texto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bibliotecas',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='libro',
            name='nombre_libro',
            field=models.CharField(max_length=100),
        ),
    ]
