# Generated by Django 4.0.4 on 2022-05-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familiares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='vinculo',
            field=models.CharField(default='holi', max_length=40),
        ),
    ]
