# Generated by Django 4.0.4 on 2022-05-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='SKU',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
