# Generated by Django 4.0.4 on 2022-06-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliotecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('provincia', models.CharField(max_length=40)),
                ('localidad', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
