# Generated by Django 4.0.4 on 2022-06-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NuevaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibliotecas',
            name='description',
        ),
        migrations.AddField(
            model_name='bibliotecas',
            name='apertura',
            field=models.CharField(default='holi', max_length=100),
        ),
        migrations.AddField(
            model_name='bibliotecas',
            name='link',
            field=models.CharField(default='holi', max_length=100),
        ),
    ]
