# Generated by Django 4.0.4 on 2022-06-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NuevaApp', '0003_alter_bibliotecas_apertura_alter_bibliotecas_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bibliotecas',
            old_name='name',
            new_name='nombre',
        ),
    ]
