# Generated by Django 4.0.4 on 2022-06-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NuevaApp', '0004_rename_name_bibliotecas_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliotecas',
            name='imagen',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
