# Generated by Django 4.0.4 on 2022-06-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NuevaApp', '0005_bibliotecas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliotecas',
            name='imagen',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
